import Header from "./components/Header";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./lib/registry";
import { GlobalStyle } from "./GlobalStyle";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Tripma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <GlobalStyle/>
          <Header />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
